// Exact shapes of the model arena report (GET /model-lab/arena, `data`) and of the extended
// scenario response (POST /model-lab/simulate, `data`). Generated by hand from models/arena.json
// and api/model_lab.py; ml/arena.py and tests/test_model_arena.py keep the JSON honest.
// Every number comes from the frozen models or the data; render nothing that is not in here.

export type Family = "baseline" | "linear" | "forest" | "boosting";
export type TaskId = "risk" | "time_to_degree" | "career" | "salary";
export type CareerClass = "Employed" | "Continuing education" | "Still seeking";
/** [first, last] graduation year, inclusive. */
export type YearRange = [number, number];

/** The API envelope every product route returns. */
export interface Envelope<T> {
  mock: false;
  model_version: string;
  data: T;
}

// ---------------------------------------------------------------------------------------
// GET /model-lab/arena
// ---------------------------------------------------------------------------------------
export interface ArenaReport {
  schema_version: 1;
  dataset: {
    name: string;
    synthetic: true;
    alumni: number;
    current_students_in_training: 0;
    /** Show this wherever arena results appear. */
    disclaimer: string;
  };
  seed: number;
  protocol: {
    temporal: true;
    same_rows_for_every_family: true;
    features_fixed_before_scoring: true;
    test_years: YearRange;
    /** Four plain-English sentences describing the protocol, in order. */
    steps: string[];
  };
  /** Simplest to most complex; `complexity` is the index. */
  families: { id: Family; label: string; complexity: number }[];
  tasks: {
    risk: RiskTask;
    time_to_degree: TimeToDegreeTask;
    career: CareerTask;
    salary: SalaryTask;
  };
}

/** Bootstrap comparison of one model against another on the test holdout. */
export interface Gain {
  /** Improvement over the reference; positive is better for every metric (loss saved, AUROC gained). */
  delta: number;
  /** 95% paired-bootstrap interval of the improvement. */
  ci95: [number, number];
  /** True only when the whole interval is above zero. */
  beats: boolean;
}

export interface ChampionBlock {
  family: Family;
  label: string;
  task: TaskId;
  /** Always a boolean; false when the champion IS the baseline (it cannot beat itself). */
  beats_baseline: boolean;
  /** null unless the champion is the random forest or gradient boosting. */
  beats_linear: boolean | null;
  /** Best family on the test holdout by the task's primary metric; may differ from the champion. */
  holdout_best_family: Family;
  /** Plain-English verdict, including when the shipped model did not earn its place. */
  note: string;
}

export interface Selection {
  /** The rule was fixed before any candidate was scored. */
  pre_registered: true;
  metric: string;
  higher_is_better: boolean;
  /** The champion is the simplest family within this relative distance of the best validation score. */
  tolerance_relative: number;
  complexity_order: Family[];
  rule: string;
  /** Validation score per family (metric above). */
  scores: Record<Family, number>;
  /** Families within tolerance of the best; the simplest becomes the champion. */
  eligible: Family[];
  champion: Family;
  test_used_for_selection: false;
  fit_years: YearRange;
  validation_years: YearRange;
  /** risk / time_to_degree: validation rows per stage. career / salary: validation rows. */
  n_validation_per_stage?: number[];
  n_validation?: number;
}

export interface Candidate<M, Extra = object> {
  family: Family;
  label: string;
  /** What this family is for this task, in words. */
  kind: string;
  complexity: number;
  /** Fixed settings; baseline is {}. */
  hyperparameters: Record<string, number | string | boolean>;
  is_champion: boolean;
  /** Headline metrics on the test holdout (risk, time_to_degree: at the task's headline stage). */
  metrics: M;
  vs_baseline: Gain | null; // null for the baseline itself
  beats_baseline: boolean;
  vs_linear: Gain | null; // null for baseline and linear
  beats_linear: boolean | null;
  validation: { score: number } & Extra;
}

export interface FeatureImportance {
  feature: string;
  label: string;
  /** Drop in the task's score when the column is shuffled on the holdout; larger is more important. */
  importance: number;
  std: number;
}

export interface ModelCard {
  name: string;
  predicts: string;
  summary: string;
  features: { name: string; label: string }[];
  limitations: string[];
  should_not_be_used_for: string[];
}

export interface Curve {
  fpr: number[];
  tpr: number[];
  auc: number;
}

/** Equal-count bins of predicted risk against the observed rate; the baseline has one point. */
export interface CalibrationCurve {
  predicted: number[];
  observed: number[];
  n: number[];
}

export interface StageSplit {
  stage: number;
  n_fit: number;
  n_validation: number;
  n_train: number;
  n_calibration: number;
  n_test: number;
  base_rate_test: number;
}

// ---- risk (per stage k = 0..6 completed terms) -------------------------------------------
export interface RiskMetrics {
  auroc: number;
  auprc: number;
  brier: number;
  log_loss: number;
  /** Slope of logit(observed) on logit(predicted); 1 is ideal. null for the baseline, which has no spread. */
  calibration_slope: number | null;
  base_rate: number;
  n_test: number;
}

export interface RiskCandidate
  extends Candidate<RiskMetrics, { per_stage: { stage: number; auroc: number }[] }> {
  per_stage: { stage: number; n_test: number; auroc: number; auprc: number; brier: number; log_loss: number }[];
  curves: {
    /** Keyed by stage as a string ("0".."6"). */
    roc: Record<string, Curve>;
    calibration: Record<string, CalibrationCurve>;
  };
}

export interface RiskTask {
  champion: ChampionBlock;
  candidates: RiskCandidate[];
  importance: {
    /** The champion, or the best learned family when the champion is the baseline. */
    family: Family;
    note: string;
    metric: string;
    /** Keyed by stage as a string; top 8 features, columns that never vary at a stage are omitted. */
    by_stage: Record<string, FeatureImportance[]>;
  };
  selection: Selection;
  split: {
    stages: number[];
    fit_years: YearRange;
    validation_years: YearRange;
    train_years: YearRange;
    calibration_years: YearRange;
    test_years: YearRange;
    per_stage: StageSplit[];
  };
  card: ModelCard & {
    trained_on: {
      rows_train: number;
      rows_calibration: number;
      rows_test: number;
      train_years: YearRange;
      calibration_years: YearRange;
      test_years: YearRange;
    };
  };
}

/** The stage the leaderboard opens on: enrollment only. Later stages partly read the label. */
export const RISK_HEADLINE_STAGE = 0;
export const TTD_HEADLINE_STAGE = 1;

// ---- quantile tasks: time to degree (years) and salary (nominal dollars) ---------------------
export interface QuantileMetrics {
  /** Mean absolute error of the median. */
  mae: number;
  /** Mean pinball loss over p25, p50, p75. */
  pinball: number;
  /** Share of holdout rows inside the p25-p75 range; a well-calibrated range is near 0.5. */
  interval_coverage: number;
  r2: number;
  /** Mean signed error of the median (prediction minus actual). */
  bias: number;
  mae_baseline: number;
  n_test: number;
}

export interface QuantileScatter {
  n_total: number;
  n_shown: number;
  actual: number[];
  /** Same rows for every family. */
  families: Record<Family, { low: number[]; mid: number[]; high: number[] }>;
}

export interface TimeToDegreeTask {
  champion: ChampionBlock;
  candidates: (Candidate<QuantileMetrics, { per_stage: { stage: number; pinball: number }[] }> & {
    per_stage: {
      stage: number;
      n_test: number;
      mae: number;
      pinball: number;
      interval_coverage: number;
    }[];
  })[];
  importance: {
    family: Family;
    note: string;
    metric: string;
    by_stage: Record<string, FeatureImportance[]>;
  };
  /** Holdout rows at the headline stage (1), in years. */
  scatter: QuantileScatter & { stage: number };
  selection: Selection;
  split: {
    stages: number[];
    fit_years: YearRange;
    validation_years: YearRange;
    train_years: YearRange;
    calibration_years: null;
    test_years: YearRange;
    per_stage: StageSplit[];
  };
  card: ModelCard & {
    trained_on: { rows_train: number; rows_test: number; train_years: YearRange; test_years: YearRange };
  };
}

// ---- career destination (three classes; No Response and Military are never classes) ------
export interface CareerMetrics {
  macro_f1: number;
  accuracy: number;
  top2_accuracy: number;
  log_loss: number;
  n_test: number;
}

export interface CareerCandidate extends Candidate<CareerMetrics> {
  per_class: Record<CareerClass, { precision: number; recall: number; f1: number; support: number }>;
  confusion: {
    /** Rows are actual classes, columns predicted, in this order. */
    labels: CareerClass[];
    row_normalised: number[][];
    counts: number[][];
  };
  /** One-vs-rest ROC per class. */
  roc: Record<CareerClass, Curve>;
}

export interface CareerTask {
  champion: ChampionBlock;
  candidates: CareerCandidate[];
  importance: {
    family: Family;
    note: string;
    metric: string;
    /** Empty only if no input varies; the baseline champion shows the best learned family instead. */
    features: FeatureImportance[];
  };
  selection: Selection;
  split: {
    fit_years: YearRange;
    validation_years: YearRange;
    train_years: YearRange;
    calibration_years: null;
    test_years: YearRange;
    n_fit: number;
    n_validation: number;
    n_train: number;
    n_test: number;
  };
  card: ModelCard & {
    trained_on: {
      rows_train: number;
      rows_test: number;
      train_years: YearRange;
      test_years: YearRange;
      class_counts: Record<CareerClass, number>;
      /** Unknown, never an outcome. */
      no_response_excluded: number;
      military_excluded: number;
    };
  };
}

export interface SalaryTask {
  champion: ChampionBlock;
  candidates: Candidate<QuantileMetrics>[];
  importance: {
    family: Family;
    note: string;
    metric: string;
    features: FeatureImportance[];
  };
  /** Holdout rows in nominal dollars. */
  scatter: QuantileScatter;
  selection: Selection;
  split: {
    fit_years: YearRange;
    validation_years: YearRange;
    train_years: YearRange;
    calibration_years: null;
    test_years: YearRange;
    n_fit: number;
    n_validation: number;
    n_train: number;
    n_test: number;
  };
  card: ModelCard & {
    trained_on: {
      rows_train: number;
      rows_test: number;
      train_years: YearRange;
      test_years: YearRange;
      /** Median first salary of each training class, nominal dollars of that year. */
      median_salary_by_year: Record<string, number>;
    };
  };
}

// ---------------------------------------------------------------------------------------
// POST /model-lab/simulate
// ---------------------------------------------------------------------------------------
/** Request body. Every field is optional; defaults are the ones shown. */
export interface ModelLabScenario {
  major: "Computer Science" | "Information Systems"; // Computer Science
  entry_type: "Transfer" | "First-Time Freshman"; // First-Time Freshman
  residency: "In-State" | "Out-of-State"; // In-State
  work_hours: number; // 0-50, 15
  completed_terms: number; // 0-6, 3
  credits_per_term: number; // 3-18, 12
  /** 0.5-1, default 1. Credits are only lost to withdrawn or failed courses in the data, so a shortfall
   *  the two counts below do not explain is counted as further withdrawals (see `effective`). */
  earned_ratio: number;
  withdrawals: number; // 0-10, 0. Apply to the completed terms only.
  failures: number; // 0-10, 0
  enrollment_gaps: number; // 0-4, 0. Only moves the trajectory pattern.
  internship_count: number; // 0-4, 1
  credential_count: number; // 0-8, 1. Held at the training maximum (3); see `out_of_range`.
  engagement_count: number; // 0-20, 3. Held at the training maximum (10).
}

export interface Driver {
  feature: "work_hours" | "credits_per_term" | "withdrawals" | "failures" | "earned_ratio" | "entry_type" | "residency" | "major";
  label: string;
  /** The scenario's value. */
  value: number | string;
  /** The typical alumnus value it was compared against (data median or most common category). */
  reference: number | string;
  /** Champion risk with this one input at the reference. */
  risk_at_reference: number;
  /** risk minus risk_at_reference, in probability (0.09 = 9 points). Positive raises risk. */
  delta: number;
  direction: "raises" | "lowers";
}

export interface CandidateChampions {
  risk: Family;
  time_to_degree: Family;
  career: Family;
  salary: Family;
}

interface CandidateTag {
  family: Family;
  label: string;
  is_champion: boolean;
}

/** Every family's answer to the same scenario, in family order (baseline first). */
export interface SimulateCandidates {
  champions: CandidateChampions;
  risk: (CandidateTag & { risk: number })[];
  time_to_degree: (CandidateTag & { low: number; mid: number; high: number })[];
  career: (CandidateTag & { probabilities: { label: CareerClass; probability: number }[] })[];
  salary: (CandidateTag & { low: number; mid: number; high: number })[];
}

export interface SimulateResponse {
  /** The request as sent. */
  scenario: ModelLabScenario;
  /** What the models actually saw. */
  effective: {
    withdrawals: number;
    failures: number;
    /** Realised share of attempted credits earned over the completed terms. */
    earned_ratio: number;
    credits_per_lost_course: number;
    work_hours: number;
    credential_count: number;
    engagement_count: number;
  };
  /** Request fields held at the edge of the training range. */
  out_of_range: ("work_hours" | "internship_count" | "credential_count" | "engagement_count")[];
  /** Champion academic risk in [0, 1]. */
  risk: number;
  risk_is_probability: boolean;
  /** Champion range in years. */
  time_to_degree: { low: number; mid: number; high: number };
  /** Stages 0..6. Stages after `completed_terms` are projected: same load, no new withdrawals. */
  trajectory: {
    term: number;
    risk: number;
    years_low: number;
    years_mid: number;
    years_high: number;
    projected: boolean;
  }[];
  /** Champion career probabilities, largest first. The baseline champion returns class frequencies. */
  career: { label: CareerClass; probability: number }[];
  /** Champion first-salary range, nominal dollars; `support` is the training row count. */
  salary: { low: number; mid: number; high: number; support: number };
  pattern: string;
  constellation: {
    points: { x: number; y: number; pattern: string }[];
    you: { x: number; y: number; pattern: string | null };
  };
  /** Up to four inputs moving the risk, largest first; empty when the scenario is typical. */
  drivers: Driver[];
  drivers_basis: string;
  candidates: SimulateCandidates;
  models: { task: TaskId; name: string; family: Family; kind: string; support: number }[];
  tool_result_id: string;
  disclaimer: string;
}
